/**
 * Serialization types for persistent conversations.
 *
 * These interfaces define the structured format for saving and resuming
 * conversations. Designed to map cleanly to both JSON files and the
 * PostgreSQL schema in docs/database-plan.md.
 *
 * ## Data flow
 *
 * After each turn the Conversation class builds a full SerializedConversation
 * snapshot and hands it to every attached ConversationWriter. Writers persist
 * the snapshot however they like (JSON file, database row, etc.).
 *
 * To resume, the caller reads the snapshot back (from file, DB, …) and passes
 * it to `Conversation.resume()`. The class validates it, restores provider
 * state, and optionally re-uploads files if the provider changed.
 *
 * ## Version compatibility
 *
 * `CONVERSATION_FORMAT_VERSION` is bumped when the schema changes in a
 * breaking way. `validateSerializedConversation()` rejects data whose
 * `formatVersion` exceeds the version this code understands, so older library
 * versions fail fast rather than silently misinterpreting newer data.
 */

import type { CodeArtifact } from "./types.js";
import type { Provider } from "./key-pool.js";

export type { Provider };

/** Current schema version. Bump when making breaking changes to the serialized format. */
export const CONVERSATION_FORMAT_VERSION = 1;

/**
 * Provider-specific opaque state needed to resume a conversation natively.
 *
 * Only the fields for the *active* provider are populated after a given turn.
 * When resuming on the same provider, these fields let the Conversation class
 * pick up exactly where it left off (e.g. continuing in the same Claude
 * container, or chaining OpenAI responses via `previous_response_id`).
 *
 * When switching to a different provider the native state is ignored and the
 * text history is reconstructed instead (see `Conversation.reconstructForNewProvider`).
 */
export interface ProviderState {
  /** Claude: raw API messages array (content blocks, not plain strings) */
  claudeMessages?: any[];
  /** Claude: sandbox container ID (expires after ~1-2 hours) */
  claudeContainerId?: string;

  /** OpenAI: opaque response ID for `previous_response_id` chaining */
  openaiResponseId?: string;
  /** OpenAI: container ID (for file downloads) */
  openaiContainerId?: string;
  /** OpenAI: full response output array (interleaved tool calls + messages) */
  openaiOutput?: any[];

  /** Gemini: raw `contents[]` array (role + parts) */
  geminiContents?: any[];
}

/**
 * Record of a file uploaded by the user during the conversation.
 *
 * Created by `Conversation.uploadFile()` / `uploadFileFromBuffer()` and
 * included in the serialized output. If `persistUploadData` is enabled
 * (default: true), `base64Data` contains the original file content so
 * the file can be re-uploaded to a different provider on resume.
 */
export interface UploadRecord {
  /** Provider-specific file identifier (e.g. Claude file ID, OpenAI file ID, Gemini URI). */
  fileId: string;
  /** Original filename (e.g. "sample.csv"). */
  filename: string;
  /** MIME type of the file (e.g. "text/csv"). */
  mimeType: string;
  /** File size in bytes. */
  sizeBytes: number;
  /** Which provider this file was uploaded to. */
  provider: Provider;
  /** ISO-8601 timestamp of when the upload occurred. */
  uploadedAt: string;
  /**
   * Base64-encoded content of the original file.
   * Populated when `persistUploadData` is true (the default).
   * Required for automatic file re-upload on provider switch.
   */
  base64Data?: string;
}

/**
 * A file generated by code execution during a turn (e.g. a plot image).
 *
 * For Gemini, `base64Data` is always present because Gemini returns files
 * as inline base64. For Claude and OpenAI, `base64Data` is captured by
 * downloading the file from the provider's API immediately after the turn
 * completes, so that generated files survive container expiry and can be
 * re-uploaded on provider switch.
 */
export interface StoredFile {
  /** Provider-specific file identifier. */
  fileId: string;
  /** Filename (e.g. "plot.png"). May be auto-generated if the provider didn't supply one. */
  filename: string;
  /** OpenAI container ID (needed to download the file via OpenAI's API). */
  containerId?: string;
  /** MIME type (e.g. "image/png"). */
  mimeType?: string;
  /** Base64-encoded file content. Always present after a successful turn. */
  base64Data?: string;
}

/**
 * Record of a single completed turn (one user message + one assistant response).
 *
 * Turns are only recorded after the provider call succeeds — a failed API
 * call never produces a TurnRecord. This makes turns a reliable log of what
 * actually happened.
 *
 * `providerStateAfter` is a snapshot of the provider-specific state at the
 * end of this turn. To resume the conversation on the same provider, restore
 * this state. To resume on a different provider, ignore it and use
 * `textHistory` instead.
 */
export interface TurnRecord {
  /** Sequential turn number (1-based). */
  turnNumber: number;
  /** ISO-8601 timestamp when the turn started (before the API call). */
  startedAt: string;
  /** ISO-8601 timestamp when the turn completed (after the API call). */
  completedAt: string;
  /** The user's message text. */
  userMessage: string;
  /** File IDs that were attached to this turn via `SendOptions.fileIds`. */
  attachedFileIds: string[];
  /** The assistant's full text response. */
  assistantText: string;
  /** Source code blocks extracted from the assistant's response. */
  codeArtifacts: CodeArtifact[];
  /** Files generated during code execution (plots, data files, etc.). */
  generatedFiles: StoredFile[];
  /** Which provider handled this turn. */
  provider: Provider;
  /** Model used for this turn (e.g. "claude-sonnet-4-5-20250929"). */
  model?: string;
  /** Snapshot of provider-specific state AFTER this turn — resume from this point. */
  providerStateAfter: ProviderState;
}

/**
 * The complete serialized conversation — the "save file" format.
 *
 * This is the top-level structure that Writers persist and that
 * `Conversation.resume()` / `Conversation.loadFromFile()` accept.
 * It contains everything needed to reconstruct a Conversation:
 * metadata, all turns with their provider state, all uploads,
 * and the provider-agnostic text history for cross-provider switching.
 *
 * ```
 * ┌─────────────────────────────────────────┐
 * │  SerializedConversation                  │
 * │  ├─ metadata (id, provider, timestamps)  │
 * │  ├─ uploads[]          ← UploadRecord    │
 * │  ├─ turns[]            ← TurnRecord      │
 * │  │  └─ providerStateAfter                │
 * │  │  └─ generatedFiles  ← StoredFile      │
 * │  └─ textHistory[]      ← role + content  │
 * └─────────────────────────────────────────┘
 * ```
 */
export interface SerializedConversation {
  /** Schema version — validated on load to prevent misinterpretation. */
  formatVersion: number;
  /** Unique conversation ID (UUID). */
  id: string;
  /** The provider that was active when this snapshot was taken. */
  provider: Provider;
  /** Model override, if set. */
  model?: string;
  /** Max tokens override, if set. */
  maxTokens?: number;
  /** ISO-8601 timestamp of conversation creation. */
  createdAt: string;
  /** ISO-8601 timestamp of last turn completion. */
  updatedAt: string;
  /** Arbitrary caller-supplied metadata (experiment ID, participant ID, etc.). */
  metadata?: Record<string, any>;
  /** All files uploaded by the user during this conversation. */
  uploads: UploadRecord[];
  /** All completed turns, in order. */
  turns: TurnRecord[];
  /**
   * Provider-agnostic text history: a flat list of user/assistant messages.
   * Used to reconstruct context when switching to a different provider.
   */
  textHistory: { role: "user" | "assistant"; content: string }[];
}

/**
 * Validate and type-narrow data loaded from a file or database.
 *
 * Checks structural invariants (required fields, correct types, supported
 * format version). Does NOT deep-validate individual turns or uploads —
 * just enough to prevent crashes when the Conversation class reads the data.
 *
 * @throws {Error} If the data is null, missing required fields, has an
 *   unsupported format version, or has an invalid provider.
 * @returns The input data, narrowed to `SerializedConversation`.
 */
export function validateSerializedConversation(data: unknown): SerializedConversation {
  if (data === null || typeof data !== "object") {
    throw new Error("Invalid conversation data: expected an object");
  }

  const obj = data as Record<string, unknown>;

  if (typeof obj.formatVersion !== "number") {
    throw new Error("Invalid conversation data: missing or invalid formatVersion");
  }
  if (obj.formatVersion > CONVERSATION_FORMAT_VERSION) {
    throw new Error(
      `Unsupported format version ${obj.formatVersion} (max supported: ${CONVERSATION_FORMAT_VERSION})`
    );
  }
  if (typeof obj.id !== "string" || !obj.id) {
    throw new Error("Invalid conversation data: missing id");
  }
  if (!["anthropic", "openai", "gemini"].includes(obj.provider as string)) {
    throw new Error("Invalid conversation data: invalid provider");
  }
  if (!Array.isArray(obj.turns)) {
    throw new Error("Invalid conversation data: turns must be an array");
  }
  if (!Array.isArray(obj.textHistory)) {
    throw new Error("Invalid conversation data: textHistory must be an array");
  }
  if (!Array.isArray(obj.uploads)) {
    throw new Error("Invalid conversation data: uploads must be an array");
  }

  return data as SerializedConversation;
}
